version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/opt/zookeeper-3.4.6/data

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "enseignant-event-topic:1:1"
      KAFKA_LISTENER_IP_EXTERNAL: docker.for.mac.localhost  # Ajoutez cette ligne pour spécifier l'adresse IP de l'hôte Docker

  mysql:
    image: mysql:latest
    ports:
      - "3308:3307"
    environment:
      MYSQL_ROOT_PASSWORD: issat2020
      MYSQL_DATABASE: enseignant

  spring-boot-app:
    image: producer:latest  # Remplacez par le nom de votre image Docker pour l'application Spring Boot
    depends_on:
      - kafka
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/enseignant
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: issat2020
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_PRODUCER_PROPERTIES_PARTITIONER_CLASS: org.apache.kafka.clients.producer.RoundRobinPartitioner
      SERVER_PORT: 8081

volumes:
  zookeeper-data:
